# -*- coding: utf-8 -*-
"""bank-account.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1efMF8a5F2df-zBEQ5IMXKPG_G09Z_nFm
"""

#Pour s'assurer que chaque instance de la classe Account possède un numéro de compte unique
import random

#Définissons la classe Account et ses attributs
class Account:
    def __init__(self, account_number, account_holder, initial_balance=0):
        self.account_number = account_number
        self.account_holder = account_holder
        self.account_balance = initial_balance

#Définissons la methode deposit.

    def deposit(self, amount):
        if amount > 0:
            self.account_balance += amount
            return True
        else:
            return False

#Définissons la methode withdraw

    def withdraw(self, amount):
        if amount > 0 and self.account_balance >= amount:
            self.account_balance -= amount
            return True
        else:
            return False

#Définissons la methode check balance

    def check_balance(self):
        return self.account_balance

# Fonction pour créer un compte avec un numéro de compte spécifié
def create_account(account_holder, account_number):
    return Account(account_number, account_holder)

# Fonction pour vérifier si le nom contient uniquement des lettres
def is_valid_name(name):
    return all(char.isalpha() or char.isspace() for char in name)

# Demander à l'utilisateur de saisir son numéro de compte et son nom
account_number = input("Veuillez entrer votre numéro de compte : ")
account_holder = input("Veuillez entrer votre nom : ")


my_account = create_account(account_holder, account_number)

# Demandez à l'utilisateur de choisir une opération
while True:
    print("Veuillez choisir une opération :")
    print("1. Vérifier le solde")
    print("2. Déposer de l'argent")
    print("3. Retirer de l'argent")
    print("4. Quitter")

    choice = input("Entrez le numéro de l'opération : ")

    if choice == "1":
        # Vérifier le solde
        balance = my_account.check_balance()
        print(f"Le solde actuel de votre compte est de : {balance}")
    elif choice == "2":
        # Déposez de l'argent
        deposit_amount = float(input("Veuillez entrer le montant à déposer : "))
        if my_account.deposit(deposit_amount):
            print(f"Dépôt effectué avec succès. Vous avez déposé {deposit_amount} dans votre compte.")
        else:
            print("Montant de dépôt invalide.")
    elif choice == "3":
        # Retirez de l'argent
        withdraw_amount = float(input("Veuillez entrer le montant à retirer : "))
        if my_account.withdraw(withdraw_amount):
            print(f"Retrait effectué avec succès. Vous avez retiré {withdraw_amount} de votre compte.")
        else:
            print("Désolé cette opération ne peut s'effectuer.Veuillez entrer un montant inférieur ou égal à au solde de votre compte.")
    elif choice == "4":
        # Quitter le programme
        print("Merci et à la prochaine.")
        break
    else:
        print("Opération non valide. Veuillez choisir une opération valide.")